### ISSUE TITLE
regions unexplored incompatibility

### ISSUE THREAD

**Issue by KostromDan** [bl4ckscor3/SnowUnderTrees#11]
![image](https://github.com/bl4ckscor3/SnowUnderTrees/assets/90044015/8b66a110-2daa-47e8-b2a7-15887fdcb190)

**Comment by bl4ckscor3** [comment]
Which biome is that?

**Comment by KostromDan** [comment]
> Which biome is that?

regions_unexplored:cold_boreal_forest

**Comment by bl4ckscor3** [comment]
So I found two of this same biome, where Snow Under Trees worked in one and did not work in the other. I'm confused.

-7742415927117807310
Works: /execute in minecraft:overworld run tp @s -713.46 71.03 -1680.48 345.55 24.26
Doesn't work: /execute in minecraft:overworld run tp @s 1222.29 78.52 -109.00 303.36 13.60

**Comment by bl4ckscor3** [comment]
The update will be released tomorrow for 1.19.4 and 1.20.1. If you are not using one of these two versions, you can fix it yourself by creating a datapack that removes the `"type": "minecraft:biome"` line from the file `data/snowundertrees/worldgen/placed_feature/snow_under_trees.json`.
