### ISSUE TITLE
[1.20.1] Snowfall not appearing under trees with Serene Seasons in biomes that only snow in winter

### ISSUE THREAD

**Issue by FelineAstronomer** [bl4ckscor3/SnowUnderTrees#13]
My apologies if this wasn't intended to be supported, in which case disregard this bug report.

Tested on Minecraft 1.20.1 with NeoForge 47.1.81, and also with Forge 47.2.17.

Mods included:
- Serene Seasons 1.20.1 version 9.0.0.46
- Snow Under Trees 1.20.1 version 1.4.2

Steps to reproduce:
1. Install the two mods "Serene Seasons" and "Snow Under Trees" in 1.20.1
2. Load a new world
3. Run "/season set MID_WINTER" and "/weather rain"
4. Go to nearest biome that snows in winter, such as a dark forest or regular taiga
5. Observe that snowfall does not accumulate underneath trees.

Note: Snowfall accumulating under trees does still work in normally snowy biomes.

**Comment by bl4ckscor3** [comment]
I just released the fix for this in v1.4.3.
