### ISSUE TITLE
[1.19.2] Snow is not generated under the branches of large trees from BOP/RU.

### ISSUE THREAD

**Issue by KostromDan** [bl4ckscor3/SnowUnderTrees#14]
Problem demonstration:
https://youtu.be/GxBsnbzhc_A

**Comment by bl4ckscor3** [comment]
That is intentional, as there are solid logs above the blocks that aren't covered in snow.

**Comment by KostromDan** [comment]
> That is intentional, as there are solid logs above the blocks that aren't covered in snow.

![image](https://github.com/bl4ckscor3/SnowUnderTrees/assets/90044015/e55c582b-4658-4ef1-aedb-76b89a5dfbea)
But isn't main idea of the mod that snow with help of wind comes under trees? If yes, snow should be under all trees and branches of tree shouldn't matter. Branches are inside of tree. So they shouldn't affect how snow falls.

**Comment by KostromDan** [comment]
This looks not good.
It looked better if where was complete snow layer without gaps.
