### ISSUE TITLE
Snow still appearing under trees in Winter (Serene Seasons) when snow generation is turned off

### ISSUE THREAD

**Issue by goldrat1** [bl4ckscor3/SnowUnderTrees#15]
Turning off the "Generate Snow/Ice" setting in Serene Seasons is meant to turn off the mechanic where snow will fall in non-snowy biomes during Winter. This works fine, however with Snow Under Trees installed, snow now falls only underneath trees in Winter with this config option disabled.
Screenshots taken in Mid-Winter in a Forest/Swamp biome to show what I mean:
![2024-04-13_17 43 52](https://github.com/bl4ckscor3/SnowUnderTrees/assets/45552594/4b938412-5769-4664-9015-ff1d2628e2b7)
![2024-04-13_17 47 38](https://github.com/bl4ckscor3/SnowUnderTrees/assets/45552594/e6026602-235d-4713-92d0-77769aecd9fc)

Snow only collects under trees, everywhere else is fine.
Please fix! This leads to really ugly snow-floored trees in almost any biome when it's snowing.

**Comment by goldrat1** [comment]
Ought to mention this is latest version, 1.20.1, v1.4.3, Forge

**Comment by bl4ckscor3** [comment]
This is now fixed in v1.4.4. Thank you for reporting!
