### ISSUE TITLE
Crash upon generates a world while both moonrise and serene seasons are installed

### ISSUE THREAD

**Issue by lzm11111111** [bl4ckscor3/SnowUnderTrees#18]
When both moonrise and serene seasons are installed, the game crash upon generates a world, I saw the crash log, because of the conflict between moonrise and serene season mixins.
[crash-2024-10-28_20.51.56-server.txt](https://github.com/user-attachments/files/17542659/crash-2024-10-28_20.51.56-server.txt)

**Comment by bl4ckscor3** [comment]
A fix for this has now been released as part of v1.4.6. Sorry for the delay!
