### ISSUE TITLE
升级1.21.4（来捣乱的

### ISSUE THREAD

**Issue by Nlu5E5Bl** [bl4ckscor3/SnowUnderTrees#20]
这mod啊，它善，魔改配置文件就能升级，有点基础的都能维护

**Comment by asadssaksjsi** [comment]
1.21.3下载链接都有了，github还没有，半开源的？

**Comment by bl4ckscor3** [comment]
What are the problems you are experiencing?

**Comment by qznfbnj** [comment]
弟啊，你神经啊？
Bro, you get mad?
