### ISSUE TITLE
[1.16.5] Snow under trees in non-snowy biomes (TerraForged)

### ISSUE THREAD

**Issue by MarioSMB** [bl4ckscor3/SnowUnderTrees#3]
Snow is being incorrectly generated under some trees in biomes added by TerraForged: https://i.imgur.com/RNHhruE.jpeg

The biome in the picture is `terraforged:cold_steppe`, though there may be others with the same issue.

**Comment by bl4ckscor3** [comment]
I can't reproduce this. According to your report, there should be snow under the tree in the image below.
TerraForged 0.2.9
Snow Under Trees 1.1.3
Seed 8799104215416506920
X/Y/Z 5807/80/-1190

https://i.imgur.com/L6g52qd.png

**Comment by MarioSMB** [comment]
I have just tested in a more isolated environment, and indeed, including *only* TerraForged and Snow Under Trees does not appear to reproduce the issue. However, including any mod that adds extra trees during generation (such as Pam's HarvestCraft Trees) triggers it:  
https://i.imgur.com/vFh3GPa.jpg

**Comment by bl4ckscor3** [comment]
Ok, it's caused by TerraForged having the affected biomes' precipitation set to snow. I don't know what I can do about this. A way to circumvent this issue is the exclusion list in Snow Under Tree's configuration file, which will exclude any added biomes from having snow generated under trees.

**Comment by MarioSMB** [comment]
Thanks for the indepth analysis. I feel obligated to ask: why is the issue only triggered by the addition of extra mods in generation (i.e. if it's using precipitation to tell if snow should be placed, shouldn't even the TerraForged trees have snow under them)?  

Perhaps one way to solve this would be to check the biome's temperature, as it seems anything above 0.15 won't generate snow, and the cold steppe biome is set to 0.25.

**Comment by bl4ckscor3** [comment]
That was a good pointer, thanks! I published an update.
