### ISSUE TITLE
Snow under Dynamic Trees

### ISSUE THREAD

**Issue by GrandmaPork** [bl4ckscor3/SnowUnderTrees#9]
Trees that aren't a full block wide leave some green around the edges. Could you add compatibility for this?

**Comment by bl4ckscor3** [comment]
I already have Dynamic Trees compatibility added in the mod. Which Minecraft version, which Snow Under Trees versions, and which Dynamic Trees version are you using? Can you please show an image if possible?

**Comment by GrandmaPork** [comment]
Never mind. Apparently it was disabled
